### ISSUE TITLE
How did you generate the RNA velocity flow visualization?

### ISSUE THREAD

**Issue by cyrilcros** [czbiohub-sf/zebrahub_analysis#1]
Hi,  would you mind explaining how you generate the "cell flows" based on RNA Velocity data in Supp. Video 6? Was it also done via Napari? 
I have been using your repo to build 3D UMAPs of my lab's own data, which are quite useful. I have gone through the RNA velocity notebooks, and I see how you use Plotly to generate 3D cones. I was wondering how you got from that to the flow video.
Thanks for the great preprint and commitment to open code/open data!

**Comment by royerloic** [comment]
Hi Cyril, the flow videos were made by a professional graphics designer and paid for. I don't have the code for that unfortunately, but I hope that one day we can design our own system to do that.

**Comment by cyrilcros** [comment]
Thank you for looking into this, it does look impressive.
