### ISSUE TITLE
Data conversion issues

### ISSUE THREAD

**Issue by feasiblee** [czbiohub-sf/zebrahub_analysis#2]
Hello, after finishing Sequencing_QualityControl, the data is integrated and batched. Is it done in R language? I don't seem to see the relevant data conversion code. thank you for your reply.

**Comment by yangjun9095** [comment]
Hi @feasiblee , apologies for the delayed response.
Yes, the integration over timepoints was done using R (Seurat), specifically, using reciprocal PCA. You can find the R script in here:
https://github.com/czbiohub-sf/zebrahub_analysis/blob/main/pre_processing/time_point_integration.R.
Hope this helps!
