### ISSUE TITLE
What genome reference was used? How was it processed for CellRanger?

### ISSUE THREAD

**Issue by ChristophH** [czbiohub-sf/zebrahub_analysis#5]
Hi,

Congrats to the team for having the final version of the Zebrahub paper out! It's very impressive work and a great resource.

I couldn't figure out what genome reference was used and how exactly the reference for CellRanger was built. It seems like that information is 
neither in this repo, the [protocols section](https://zebrahub.sf.czbiohub.org/protocols) of the project, nor the method section of the [paper](https://www.cell.com/cell/fulltext/S0092-8674(24)01147-4).

All I found was:

> To align the reads to the reference genome, a reference genome was first created using CellRanger v.4.0.0. Subsequently, the CellRanger v.5.0.1 software was used for read alignment to the reference zebrafish genome.

Could you please share the commands that you used to download the reference and its annotation, and to create the CellRanger compatible reference?

Thanks,
Christoph

**Comment by yangjun9095** [comment]
Hi Christoph, 

Thank you for your question. We used the GRCz11 ([ensembl](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000002035.6/)) GTF file to generate the alignment reference. 
For CellRanger command to generate the alignment reference, please refer to this instruction [link](https://www.10xgenomics.com/support/software/cell-ranger/latest/tutorials/cr-tutorial-mr#getfiles).

Best,
Yang-Joon

**Comment by ChristophH** [comment]
Hi Yang-Joon,

Which genome annotation did you use? The link that you posted is directing to NCBI and contains the RefSeq annotation (GCF_000002035.6-RS_2024_08) from Aug 15, 2024 - this is quite recent and not what you used, I think. Did you use the ensembl annotation, and if so, which release?

**Comment by Evenlyeven** [comment]
> Hi Yang-Joon,
> 
> Which genome annotation did you use? The link that you posted is directing to NCBI and contains the RefSeq annotation (GCF_000002035.6-RS_2024_08) from Aug 15, 2024 - this is quite recent and not what you used, I think. Did you use the ensembl annotation, and if so, which release?

I am looking for this information too! Did you happen to find out more info on this?

Thanks,
Di
